hall:
  chat:
    xmpp:
      smack:
        debug: false
      name: finomen
      server:
        port: 5222
        host: kt15.ru
      password: Schadel
      room: neerc@conference.kt15.ru
      service: neerc.kt15.ru
      ping:
        enabled: true
        interval: 5
    window:
      sendByEnter: true
