network:
  ServerHost: 127.0.0.1
  ServerPort: 7777
timeFormat:
  "5:00:00" : H:MM:SS
  "59:00": MM:SS
  "59":  S
colorScheme:
  "5:00:00": Salmon
fontScheme:
  "5:00:00": Alien Encounters
backgrounds:
  "5:00:00": resources/background.jpg
network:
  udp-port: 6767
  multicast-group: 225.0.0.1
  multicats-iface: eth3
  server-host: 127.0.0.1
  server-port: 6768